export const fallbackDashboard = {
  generatedAt: new Date().toISOString(),
  yearStart: 2023,
  yearEnd: 2026,
  summary: {
    totalPapers: 6,
    conferences: [
      { id: 'acl', name: 'ACL' },
      { id: 'emnlp', name: 'EMNLP' },
      { id: 'iclr', name: 'ICLR' },
      { id: 'icml', name: 'ICML' },
      { id: 'neurips', name: 'NeurIPS' },
      { id: 'naacl', name: 'NAACL' },
    ],
    years: [2023, 2024, 2025, 2026],
    categories: [
      { id: 'llms', label: 'LLMs & Foundation Models', color: '#2563eb' },
      { id: 'multimodal', label: 'Multimodal & Vision-Language', color: '#7c3aed' },
      { id: 'alignment_safety', label: 'Alignment, Safety & Trust', color: '#dc2626' },
      { id: 'evaluation', label: 'Evaluation & Benchmarks', color: '#4f46e5' },
      { id: 'agents_tools', label: 'Agents & Tool Use', color: '#0f766e' },
      { id: 'efficient_ai', label: 'Efficient AI & Systems', color: '#16a34a' },
    ],
    categoryTotals: [
      { id: 'llms', label: 'LLMs & Foundation Models', color: '#2563eb', count: 2, share: 0.33 },
      { id: 'multimodal', label: 'Multimodal & Vision-Language', color: '#7c3aed', count: 1, share: 0.17 },
      { id: 'alignment_safety', label: 'Alignment, Safety & Trust', color: '#dc2626', count: 1, share: 0.17 },
      { id: 'evaluation', label: 'Evaluation & Benchmarks', color: '#4f46e5', count: 1, share: 0.17 },
      { id: 'agents_tools', label: 'Agents & Tool Use', color: '#0f766e', count: 1, share: 0.17 },
    ],
    conferenceYearMatrix: [
      { conference: 'acl', conferenceName: 'ACL', year: 2023, total: 1, tracks: { main: 1, findings: 0 }, categories: { llms: 1 } },
      { conference: 'emnlp', conferenceName: 'EMNLP', year: 2024, total: 1, tracks: { main: 0, findings: 1 }, categories: { evaluation: 1 } },
      { conference: 'iclr', conferenceName: 'ICLR', year: 2026, total: 1, tracks: { main: 1, findings: 0 }, categories: { agents_tools: 1 } },
      { conference: 'icml', conferenceName: 'ICML', year: 2025, total: 1, tracks: { main: 1, findings: 0 }, categories: { efficient_ai: 1 } },
      { conference: 'neurips', conferenceName: 'NeurIPS', year: 2025, total: 1, tracks: { main: 1, findings: 0 }, categories: { multimodal: 1 } },
      { conference: 'naacl', conferenceName: 'NAACL', year: 2025, total: 1, tracks: { main: 0, findings: 1 }, categories: { alignment_safety: 1 } },
    ],
    yearlyTopicSeries: [
      { year: 2023, total: 1, categories: { llms: { count: 1, share: 1 } } },
      { year: 2024, total: 1, categories: { evaluation: { count: 1, share: 1 } } },
      { year: 2025, total: 3, categories: { multimodal: { count: 1, share: 0.33 }, efficient_ai: { count: 1, share: 0.33 }, alignment_safety: { count: 1, share: 0.33 } } },
      { year: 2026, total: 1, categories: { agents_tools: { count: 1, share: 1 } } },
    ],
    momentum: [
      { id: 'agents_tools', label: 'Agents & Tool Use', color: '#0f766e', delta: 0.2, recentShare: 0.2, baselineShare: 0, recentCount: 1 },
      { id: 'multimodal', label: 'Multimodal & Vision-Language', color: '#7c3aed', delta: 0.2, recentShare: 0.2, baselineShare: 0, recentCount: 1 },
      { id: 'alignment_safety', label: 'Alignment, Safety & Trust', color: '#dc2626', delta: 0.2, recentShare: 0.2, baselineShare: 0, recentCount: 1 },
    ],
    sourceCoverage: [],
  },
  papers: [
    {
      id: 'sample-1',
      title: 'Instruction Tuning for Reliable Language Models',
      authors: ['Sample Author'],
      year: 2023,
      conference: 'acl',
      conferenceName: 'ACL',
      track: 'main',
      trackLabel: 'Main',
      source: 'Fallback',
      url: '#',
      keywords: ['language model'],
      primaryCategory: 'llms',
      categories: ['llms'],
    },
  ],
};
